variables:
    - group: Test-Variable-Group-AzConfig

trigger:
- master

jobs:
- template: test.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'
    connectionString: $(AZ_CONFIG_CONNECTION)

- template: test.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'
    connectionString: $(AZ_CONFIG_CONNECTION)

- template: test.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    connectionString: $(AZ_CONFIG_CONNECTION)

- job: 'Publish'

  dependsOn:
  - 'Test_Linux'
  - 'Test_macOS'
  - 'Test_Windows'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: dotnet pack --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
