variables:
 # public
 - ${{ if eq(variables['System.TeamProject'], 'public') }}:
   - name: connectionString
     value: ''
 # internal
 - ${{ if ne(variables['System.TeamProject'], 'public') }}:
   - group: AzureSDK KeyVault - AzConfig LiveTest
   - name: connectionString
     value: $(AzConfigConnection)

jobs:
- template: test.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'
    connectionString: $(connectionString)

- template: test.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'
    connectionString: $(connectionString)

- template: test.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    connectionString: $(connectionString)

- job: 'Publish'

  dependsOn:
  - 'Test_Linux'
  - 'Test_macOS'
  - 'Test_Windows'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: dotnet pack --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
