parameters:
  name: ''
  vmImage: ''
  connectionString: ''

jobs:
- job: ${{ format('Test_{0}', parameters.name) }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Test Mocks'
    condition: or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest'))
    inputs:
      projects: '**/*.Test/*.csproj'
      command: test --filter TestCategory!=Live
  
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    condition: and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest'))
    env:
      AZ_CONFIG_CONNECTION: ${{ parameters.connectionString }}
    inputs:
      projects: '**/*.Test/*.csproj'
      command: test
       
       
