parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ format('Test_{0}', parameters.name) }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: test
      projects: '**/*.Test/*.csproj'
