parameters:
  name: ''
  vmImage: ''
  connectionString: ''

jobs:
- job: ${{ format('Test_{0}', parameters.name) }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Test Mocks'
    condition: eq(variables['System.TeamProject'], 'public')
    inputs:
      projects: '**/*.Test/*.csproj'
      command: test
      arguments: --filter TestCategory!=Live
 
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    condition: ne(variables['System.TeamProject'], 'public')
    env:
      AZ_CONFIG_CONNECTION: ${{ parameters.connectionString }}
    inputs:
      projects: '**/*.Test/*.csproj'
      command: test
       
       
